---
title: "deadband"
author:
  name: Ben
date: last-modified
code-fold: true
toc: true
---

```{r setup}
#| output: false

library(lubridate)
library(tidyr)
library(fluxfinder)
options(fluxfinder.quiet = TRUE)
library(dplyr)
library(broom)
library(ggplot2)
set_theme(theme_bw())
library(readr)
```

# 2026 flood week soil GHGs

## Data prep

```{r rs2026-data-prep}

# Find the data files
files <- list.files(pattern = "json$", 
                    path = "data/",
                    full.names = TRUE) 
message("Found ", length(files), " data files")

dat_list <- list()
for(f in files) {
  message("\tReading ", f)
  ffi_read_LIsmartchamber(f) |> 
    as_tibble() |> 
    select(Collar = label, RepNum, TIMESTAMP, 
           co2, ch4, DeadBand,
           soilp_c, soilp_m, soilp_t,
           co2_F_o, ch4_F_o) |> 
    mutate(Collar = as.integer(Collar),
           AMPM = if_else(am(TIMESTAMP), "AM", "PM")) ->
    dat_list[[f]]
}
# Join everything together
dat <- bind_rows(dat_list)
message("Read ", nrow(dat), " rows")

# Metadata
METADATA_FILE <- "metadata/mapping.csv"
message("Reading ", METADATA_FILE)
md <- read_csv(METADATA_FILE, col_types = "icc")
dat |> 
  left_join(md, by = "Collar") ->
  dat

# Compute 'Group' and "time_s' columns
dat$Group <- dat |> group_by(yday(TIMESTAMP), Collar, RepNum, AMPM) |> group_indices()

dat |> 
  group_by(Group) |> 
  mutate(time_s = as.numeric(TIMESTAMP - min(TIMESTAMP))) |> 
  ungroup() ->
  dat

```

## Dead band and measurement length analysis

```{r dm-ml-analysis}
dbs <- c(0, 5, 10, 15, 20)
mls <- c(30, 40, 50, 60)

RESULTS_FILE <- "results.RDS"
 if(file.exists(RESULTS_FILE)) {
   warning("Reading ", RESULTS_FILE)
   results <- readRDS(RESULTS_FILE)
 } else {
   results <- list()
   for(g in sort(unique(dat$Group))) {
     if(g %% 50 == 0) message(g)
     for(db in dbs) {
       for(ml in mls) {
         dat |> 
           # isolate this group and drop data in the dead band
           filter(Group == g, time_s > db) |> 
           # drop data beyond the measurement length
           slice_head(n = ml) ->
           this_dat
         
         suppressWarnings({
           co2_results <- fluxfinder::ffi_fit_models(this_dat$time_s, this_dat$co2)
           co2_results$Gas <- "CO2"
           ch4_results <- fluxfinder::ffi_fit_models(this_dat$time_s, this_dat$ch4)
           ch4_results$Gas <- "CH4"
         })
         bind_rows(co2_results, ch4_results) |> 
           bind_cols(tibble(Collar = this_dat$Collar[1],
                            g = g, db = db, ml = ml, n = nrow(this_dat))) ->
           results[[paste(g, db, ml)]]
       }
     }
   }
   
   results <- bind_rows(results) |> as_tibble()
   message("Saving ", RESULTS_FILE)
   saveRDS(results, file = RESULTS_FILE)   
 }


```

## Overall visualization

```{r}
results |> 
  ggplot(aes(x = lin_r.squared)) + 
  geom_histogram(bins = 30) + 
  facet_wrap(~Gas) + 
  ggtitle("Overall lin_r.squared distribution, all data")

results |> 
  ggplot(aes(x = lin_flux.estimate)) + 
  geom_histogram(bins = 30) + 
  facet_wrap(~Gas, scales = "free") + 
  ggtitle("Overall lin_flux.estimate distribution, all data")

ggplot(results |> filter(ml == max(mls)), 
       aes(db, lin_r.squared, group = g)) +
  geom_line() + 
  facet_wrap(~Gas) + 
  ggtitle(paste0("Dead band versus R2, ml=", max(mls)))

ggplot(results |> filter(db== 0), 
       aes(ml, lin_r.squared, group = g)) +
  geom_line() + 
  facet_wrap(~Gas) + 
  ggtitle("Measurement length versus R2, db=0")

```

## Detailed by-collar look

```{r by-collar-look}
#| fig-width: 10
#| fig-height: 8

# Plot, for all collars, how R2 values with changing dead band
# and measurement length (i.e., the dm-ml-analysis above)
# We plot the two gases separately; connect point by group number
# to see the effect of the changing variable; and color by overall
# trend for that collar.

# Helper function
trends <- function(p.values, estimates) {
  x <- if_else(p.values > 0.05, "None", 
          if_else(estimates < 0, "Negative", "Positive"))
  factor(x, levels = c("None", "Positive", "Negative"))
}

for(gas in unique(results$Gas)) {
  # Dead band
  # Isolate the data for this gas and full measurement length
  dat_gas_db <- results |> filter(Gas == gas, ml == max(mls))
  # ...and calculate overall trend: positive, negative, or none
  dat_gas_db |> 
    group_by(Collar) |> 
    reframe(broom::tidy(lm(lin_r.squared ~ db))) |> 
    filter(term == "db") |>
    transmute(Collar = Collar, 
              Trend = trends(p.value, estimate)) ->
    db_trends
  # Finaly calculate whether it's curvilinear
  # (increasing then decreasing)
  # TODO
  
  # Plot and summary table
  p1 <- ggplot(dat_gas_db |> left_join(db_trends, by = "Collar"),
         aes(db, lin_r.squared, color = Trend, group = g)) +
    geom_line() +
    facet_wrap(~Collar) + 
    theme(strip.text = element_text(size = 6)) +
    ggtitle(paste0(gas, " dead band effect by collar, ml=", max(mls))) +
    scale_color_manual("Overall\ntrend", drop = FALSE, 
                       values = c("black", "darkgreen", "darkred"))
  print(p1)
  
  db_trends |> 
    group_by(Trend) |> 
    summarise(N = n()) |> 
    print()
  
  # Measurement length
  # Isolate the data for this gas and dead band of zero
  dat_gas_ml <- results |> filter(Gas == gas, db == min(dbs))
  # ...and calculate overall trend: positive, negative, or none
  dat_gas_ml |> 
    group_by(Collar) |> 
    reframe(broom::tidy(lm(lin_r.squared ~ ml))) |> 
    filter(term == "ml") |>
    transmute(Collar = Collar, 
              Trend = trends(p.value, estimate)) ->
    ml_trends
  
  # Plot and summary table
  p2 <- ggplot(dat_gas_ml |> left_join(ml_trends, by = "Collar"),
         aes(ml, lin_r.squared, color = Trend, group = g)) +
    geom_line() +
    facet_wrap(~Collar) + 
    theme(strip.text = element_text(size = 6)) +
    ggtitle(paste0(gas, " measurement length effect by collar, db=", min(dbs))) +
    scale_color_manual("Overall\ntrend", drop = FALSE,
                       values = c("black", "darkgreen", "darkred"))
  print(p2)
  
  db_trends |> 
    group_by(Trend) |> 
    summarise(N = n()) |> 
    print()
}

```

## Repetitions

If we had stopped after one repetition, would we have gotten the same flux?

```{r}
# Use the Smart Chamber fluxes for this
dat |> 
  group_by(Group, RepNum, Collar) |> 
  summarise(co2_F_o = mean(co2_F_o),
            ch4_F_o = mean(ch4_F_o), .groups = "drop") ->
  dat_fluxes

dat_fluxes |> 
  filter(RepNum == 1) |> 
  rename(co2_F_o_R1 = co2_F_o, ch4_F_o_R1 = ch4_F_o) |> 
  select(-RepNum) ->
  dat_fluxes_R1

dat_fluxes |> 
  # overwrite Group numbers to be 1, 1, 3, 3, 5, 5, etc., rather than 1, 2, 3, 4...
  mutate(Group = floor((Group - 1) / 2) * 2 + 1) |> 
  group_by(Group, Collar) |> 
  summarise(co2_F_o = mean(co2_F_o), 
            ch4_F_o = mean(ch4_F_o), .groups = "drop") |> 
  left_join(dat_fluxes_R1, by = c("Group", "Collar")) ->
  dat_fluxes_reptest

ggplot(dat_fluxes_reptest, aes(co2_F_o, co2_F_o_R1)) + 
  geom_point(na.rm = TRUE) + geom_abline() + 
  geom_smooth(method = lm, na.rm = TRUE, formula = y ~ x) + 
  ggtitle("CO2 two-rep average versus first rep only")
message("t-test (N = ", nrow(dat_fluxes_reptest), "):")
t.test(dat_fluxes_reptest$co2_F_o, dat_fluxes_reptest$co2_F_o_R1, paired = TRUE)

ggplot(dat_fluxes_reptest, aes(ch4_F_o, ch4_F_o_R1)) + 
  geom_point(na.rm = TRUE) + geom_abline() + 
  geom_smooth(method = lm, na.rm = TRUE, formula = y ~ x) + 
  ggtitle("CH4 two-rep average versus first rep only") +
  facet_grid(. ~ ch4_F_o > 0, scales = "free", space = "free_x")

ch4_negative <- dat_fluxes_reptest |> filter(ch4_F_o < 0)
message("t-test (negative fluxes, N = ", nrow(ch4_negative), "):")
t.test(ch4_negative$ch4_F_o, ch4_negative$ch4_F_o_R1, paired = TRUE)
ch4_positive <- dat_fluxes_reptest |> filter(ch4_F_o >= 0)
message("t-test (positive fluxes, N = ", nrow(ch4_positive), "):")
t.test(ch4_positive$ch4_F_o, ch4_positive$ch4_F_o_R1, paired = TRUE)

```
